### ISSUE TITLE
Is it still supposed to work - Omnet 5.62 - Inet 4.2.5 ?

### ISSUE THREAD

**Issue by abondis** [Agr-IoT/LEACH#17]
Hello,
I have been having issues compiling even just inet after copying the folders.
Among the errors, one is this:
```c++
In file included from inet/routing/leach/Leach.cc:8:
inet/routing/leach/Leach.h:56:15: error: duplicate member 'event'
    cMessage *event = nullptr;
              ^
```
we see the change was introduced at some point here:
https://github.com/Agr-IoT/LEACH/blame/3d2ba86565b29f0da14f0a6473a699e47d3095de/inet/routing/leach/Leach.h#L56

Is it desired? is there a commit number that is known to work and the rest after has not yet been tested?

Thank you!

**Comment by ereszka** [comment]
I'm working on a version for INET 4.5, I don't get an error on that line, mostly had impact from inet changes

**Comment by abondis** [comment]
Hi, thanks for the reply!

So with 5.6.2 and inet 4.2.5, you are able to compile everything and run the simulation with the latest commits on the `main` branch?

**Comment by xcodeBn** [comment]
I finished a working version with inet4.5 if you want it

**Comment by ereszka** [comment]
I'm running it on omnet 6.0.2 and inet 4.5, haven't tried on inet 4.2.5; I had to modify a few things because of version changes but regardless of that there's a few issues and errors that don't depend on the version change -> like no _if_ statement for ACK packets that don't come from a CH, that results in a runtime error after a few thousand events. Now I also realized that BS packets don't contain sensor data from DATA packets.

**Comment by abondis** [comment]
@ereszka do you happen to have it published somewhere?

**Comment by ereszka** [comment]
Not yet, my project will be a multi-hop version but I could publish the standard one earlier, just need to check the licenses etc;
The plan for now is to finish fixing it by the end of the week; I'll probably be able to share it next week if all goes well

**Comment by n-jay** [comment]
@abondis, apologies for being late in getting to this. 
I've been occupied with postgrad work, so I haven't had much time to attend to project maintenance. Were you able to resolve this?

**Comment by abondis** [comment]
@n-jay no worries, thank you for the reply
I did a few modifications that seem to fix it for my setup. I have some more questions about the project, do you mind if I contact you directly?
Thanks!

**Comment by n-jay** [comment]
> I have some more questions about the project, do you mind if I contact you directly?

Of course @abondis. I've listed my personal email in my GH project. Please feel free to reach out.

> I did a few modifications that seem to fix it for my setup.

Great!
Would really appreciate it if you could provide the fix that worked for you here and close the issue for posterity.

**Comment by abondis** [comment]
thanks.

I will first validate that I didn't mess anything up, and I'll share it here if all is fine.
